var demangle = require("demangle").demangle;
console.log(demangle("__Znwj"));
console.log(demangle("__ZN2rx7adaptorIZNKS_4__12clINS_19shared_strand_makerIRNS_6strandINS_8run_loopINSt3__16chrono12steady_clockESt13exception_ptrE6strandEJNS_6detail3nowIS8_EES8_EEEEEEEDaT_EUlSJ_E_EC1ERKSL_"));
